// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9dGNKiRFUJyNgM6zzBTPU3Q_7tyTifqM',
    appId: '1:279627868095:web:f7d848df37607b45f0a30a',
    messagingSenderId: '279627868095',
    projectId: 'temp-and-moist-monitor',
    authDomain: 'temp-and-moist-monitor.firebaseapp.com',
    databaseURL: 'https://temp-and-moist-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'temp-and-moist-monitor.firebasestorage.app',
    measurementId: 'G-RD58GJ7528',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGKWdHfZKOyi-i9LvX33R_PXCD2_duQb4',
    appId: '1:279627868095:android:491ddd7cf22c774ef0a30a',
    messagingSenderId: '279627868095',
    projectId: 'temp-and-moist-monitor',
    databaseURL: 'https://temp-and-moist-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'temp-and-moist-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkNV6u5xnu8noY5-Vpw0gYfplbnht_-Tw',
    appId: '1:279627868095:ios:29114d42342e171ff0a30a',
    messagingSenderId: '279627868095',
    projectId: 'temp-and-moist-monitor',
    databaseURL: 'https://temp-and-moist-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'temp-and-moist-monitor.firebasestorage.app',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkNV6u5xnu8noY5-Vpw0gYfplbnht_-Tw',
    appId: '1:279627868095:ios:29114d42342e171ff0a30a',
    messagingSenderId: '279627868095',
    projectId: 'temp-and-moist-monitor',
    databaseURL: 'https://temp-and-moist-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'temp-and-moist-monitor.firebasestorage.app',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9dGNKiRFUJyNgM6zzBTPU3Q_7tyTifqM',
    appId: '1:279627868095:web:f80d97766efb8bdcf0a30a',
    messagingSenderId: '279627868095',
    projectId: 'temp-and-moist-monitor',
    authDomain: 'temp-and-moist-monitor.firebaseapp.com',
    databaseURL: 'https://temp-and-moist-monitor-default-rtdb.firebaseio.com',
    storageBucket: 'temp-and-moist-monitor.firebasestorage.app',
    measurementId: 'G-MJC7C25LT3',
  );

}